# Generated by Django 3.2.6 on 2022-09-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedevice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
